if (NOT DEFINED KSYSTEM_DIR)

  set (KSYSTEM_DIR "${CMAKE_BINARY_DIR}/k-system")
  file (MAKE_DIRECTORY ${KSYSTEM_DIR})

  set (KSYSTEM_INCLUDE_DIR "${KSYSTEM_DIR}/include")
  file (MAKE_DIRECTORY ${KSYSTEM_INCLUDE_DIR})

  set (KSYSTEM_BINARY_DIR "${KSYSTEM_DIR}/bin")
  file (MAKE_DIRECTORY ${KSYSTEM_BINARY_DIR})

  set (KSYSTEM_LIB_DIR "${KSYSTEM_DIR}/lib")
  file (MAKE_DIRECTORY ${KSYSTEM_LIB_DIR})

  set (KDIST_DIR "${CMAKE_BINARY_DIR}/dist")
  file (MAKE_DIRECTORY ${KDIST_DIR})

  set (KNORBA_INCLUDE_DIR "${KDIST_DIR}/include")
  file (MAKE_DIRECTORY ${KNORBA_INCLUDE_DIR})

  set (KNORBA_LIB_DIR "${KDIST_DIR}/lib")
  file (MAKE_DIRECTORY ${KNORBA_LIB_DIR})

  set (KNORBA_BINARY_DIR "${KDIST_DIR}/bin")
  file (MAKE_DIRECTORY ${KNORBA_BINARY_DIR})

  include_directories (
    ${KSYSTEM_INCLUDE_DIR}
    ${KNORBA_INCLUDE_DIR})

endif (NOT DEFINED KSYSTEM_DIR)
